apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pvc-1c60f8f9-75f7-4526-aae5-9837bd44949e
    fsType: ext4
