apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pvc-54067faa-6d85-47e3-80b7-f512fad0859c
    fsType: ext4
